### PR TITLE
Spell checker

### PR DESCRIPTION
**Pull request by QuentinRa**
#344: I only allowed some elements, instead of allowing spell checking everywhere and disabling them one by one.

image

But, I don't know why this is not working everytime (**edit**: this is because this I had `type name = value [@@something]` and `value [@@something]` is considered as a `PsiTypeBinding`. I would have to do more work to patch this, but I think this is a waste of time as the initial problem is solved)

image

### CODE REVIEW

**Comment by giraud** [comment]
thanks.
for the remaining point, it might be a parser problem, I'll check

**Comment by QuentinRa** [comment]
I don't think this is problem with your parser. I don't really understand how this is working, but

"value [@@something]" is passing a lot of time inside the function

- value: PsiTypeBinding
- @@something: PsiAnnotationImpl
- \[@@something]: PsiMacroName
- value [@@something] : PsiTypeBinding

I handled each of the first three cases, but for the last one, I'm considering a PsiTypeBinding as a String, and using a TEXT_TOKENIZER so "[@@something]" that was ignored is now spellchecked. I may have to extract back value in PsiTypeBinding as a "patch", but I don't think this would be a good idea.

**Comment by QuentinRa** [comment]
The rule was for this

image

**Comment by giraud** [comment]
yes, it's not a keyword or a construct from the language. it should be type checked.

**Comment by QuentinRa** [comment]
Done!

image

This was indeed a mistake! Sorry!

image

**Comment by giraud** [comment]
Itisamistake

**Pull request merged**
