### PR TITLE
Set Ocaml SDK outside IntelliJ

### PR DESCRIPTION
**Pull request by QuentinRa**
Hi, I'm back! I finally had time to merge my tests in your code. Unfortunately, this was not easy, as I had to remove 3 classes, namely

* OCamlSdkType
* OCamlSourcesOrderRootType
* OCamlSourcesOrderRootTypeUIFactory

To be accurate, I remade them from scratch by exploring what others did in other plugins/in Java, and I managed to make the code cleaner (at least there is less code from "us", and I'm using more classes from the API). Do you remember this comment, it was in OCamlSdkType

```
// Hack to get OCaml sources indexed like java sources
// Find a better way to do it !!
```

---

So, as I modified a lot of files, I will explain everything starting from now.

* **Goal**: being able to set the SDK using another menu, available in PyCharm/...
* **Result**: working (tested in PyCharm/PHPStorm, on Linux (Debian) and Windows), but 😔, I disabled the menu allowing someone to download the sources/use Cygwin/... (temporary, you can only add sources).

What I did was

* adding a menu next to build/run/debug/... to set the SDK, disabled (yet still visible) unless the user opened a .ml file
* adding a sort of message on IntelliJ, to remind the user to set an SDK (built-in feature)
* detecting/suggesting SDK in the list (checking C:/bin, /bin, ~/.opam, ..., according to the OS)
* allowing someone to use ocaml/ocamlc, without opam (=> they can add sources)
* sources are indexed using a small trick, and you can enjoy IntelliJ features (this is still a stupid autocompletion)

My notes

* it's not possible yet to remove an SDK outside IntelliJ (we need a menu)
* I couldn't test that everything else was still working (=> dune, ...), in practice, aside from `OCamlAdditionalDataConfigurable`-related stuff, everything is still enabled
* would be good to be able to download an SDK too

---

I'm not done yet, but now, you can see what I did.

### CODE REVIEW

**Comment by giraud** [comment]
Thanks, I'll look at that PR next few days.
you have build errors, some tests are failing

**Comment by giraud** [comment]
got an NPE:
```
java.lang.NullPointerException
	at com.reason.ide.ORProjectRootListener$1.lambda$rootsChanged$0(ORProjectRootListener.java:39)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:526)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by QuentinRa** [comment]
Sorry! I was looking as to how you got this NPE, so I tried to use my new feature in a dune project (without dune, as I yet to install it, and without a SDK), and it was not working at all 😔. I will try to work on it when I have more time 👍.

**Comment by giraud** [comment]
I forgot to add context: I was trying to set up a dune project in phpstorm

**Comment by QuentinRa** [comment]
For now, I don't think I will continue working on it, so I'm closing this. I think I will create my own plugin, taking parts of this one, for my personal use (so I won't publish it on the marketplace), as I don't have the time (nor the motivation for now), to make something that is working for everyone.

I'm enjoying working on this plugin, so I will come back, but I don't know when ✨.Until next time!

**Comment by giraud** [comment]
I understand, it's not an easy task. 
Good luck !

**Pull request closed without merging**
